function DailycubeparametersMatriXXQAreferencefrommeasurementscombinedwi = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DAILYCUBEPARAMETERSMATRIXXQAREFERENCEFROMMEASUREMENTSCOMBINEDWI =
%  IMPORTFILE(FILE) reads data from the first worksheet in the Microsoft
%  Excel spreadsheet file named FILE.  Returns the data as a cell array.
%
%  DAILYCUBEPARAMETERSMATRIXXQAREFERENCEFROMMEASUREMENTSCOMBINEDWI =
%  IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  DAILYCUBEPARAMETERSMATRIXXQAREFERENCEFROMMEASUREMENTSCOMBINEDWI =
%  IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified worksheet
%  for the specified row interval(s). Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  DailycubeparametersMatriXXQAreferencefrommeasurementscombinedwi = importfile("/Users/johanrensfeldt/Library/Mobile Documents/com~apple~CloudDocs/Scandion/data combination/matrix/01_Daily cube parameters MatriXX QA_reference from measurements_combined with DailyQA_2023-07-28.xlsx", "GTR1", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Aug-2023 16:34:07

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [10, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 43);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["DailyCubesParameters", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "Reference", "fromMeasurementsForMatrixx2", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "firstHalfOf2019", "VarName24", "VarName25", "VarName26", "VarName27", "firstHalfOf2019_1", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43"];
opts.VariableTypes = ["char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char"];

% Specify variable properties
opts = setvaropts(opts, ["DailyCubesParameters", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "Reference", "fromMeasurementsForMatrixx2", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "firstHalfOf2019", "VarName24", "VarName25", "VarName26", "VarName27", "firstHalfOf2019_1", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["DailyCubesParameters", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "Reference", "fromMeasurementsForMatrixx2", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "firstHalfOf2019", "VarName24", "VarName25", "VarName26", "VarName27", "firstHalfOf2019_1", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43"], "EmptyFieldRule", "auto");

% Import the data
DailycubeparametersMatriXXQAreferencefrommeasurementscombinedwi = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    DailycubeparametersMatriXXQAreferencefrommeasurementscombinedwi = [DailycubeparametersMatriXXQAreferencefrommeasurementscombinedwi; tb]; %#ok<AGROW>
end

%% Convert to output type
DailycubeparametersMatriXXQAreferencefrommeasurementscombinedwi = table2cell(DailycubeparametersMatriXXQAreferencefrommeasurementscombinedwi);
numIdx = cellfun(@(x) ~isnan(str2double(x)), DailycubeparametersMatriXXQAreferencefrommeasurementscombinedwi);
DailycubeparametersMatriXXQAreferencefrommeasurementscombinedwi(numIdx) = cellfun(@(x) {str2double(x)}, DailycubeparametersMatriXXQAreferencefrommeasurementscombinedwi(numIdx));
end